// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context, types} from '../models';

export function GetConfig():Promise<types.Config>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateConfig(arg1:types.Config):Promise<void>;
