// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['services']['FileService']['DeleteFile'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['services']['FileService']['DownloadFile'](arg1);
}

export function GetFileList(arg1) {
  return window['go']['services']['FileService']['GetFileList'](arg1);
}

export function GetShareUrl(arg1, arg2) {
  return window['go']['services']['FileService']['GetShareUrl'](arg1, arg2);
}

export function Mkdir(arg1, arg2) {
  return window['go']['services']['FileService']['Mkdir'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['services']['FileService']['Startup'](arg1);
}

export function UploadDir(arg1) {
  return window['go']['services']['FileService']['UploadDir'](arg1);
}

export function UploadFiles(arg1) {
  return window['go']['services']['FileService']['UploadFiles'](arg1);
}
