// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChoseDir() {
  return window['go']['services']['SyncDirService']['ChoseDir']();
}

export function CreateSyncDir(arg1, arg2) {
  return window['go']['services']['SyncDirService']['CreateSyncDir'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['services']['SyncDirService']['Startup'](arg1);
}
