// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context, types} from '../models';

export function ChoseDir():Promise<string>;

export function CreateSyncDir(arg1:string,arg2:string):Promise<types.SyncDir>;

export function Startup(arg1:context.Context):Promise<void>;
