// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function DownloadFile(arg1:string):Promise<types.Result>;

export function GetConfig():Promise<types.Result>;

export function GetFileList(arg1:string):Promise<types.Result>;

export function GetShareUrl(arg1:string,arg2:number):Promise<types.Result>;

export function Mkdir(arg1:string,arg2:string):Promise<types.Result>;

export function UpdateConfig(arg1:types.Config):Promise<types.Result>;

export function UploadFiles(arg1:string):Promise<types.Result>;
