// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFileList(arg1) {
  return window['go']['main']['App']['GetFileList'](arg1);
}

export function GetShareUrl(arg1, arg2) {
  return window['go']['main']['App']['GetShareUrl'](arg1, arg2);
}

export function Mkdir(arg1, arg2) {
  return window['go']['main']['App']['Mkdir'](arg1, arg2);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UploadFiles(arg1) {
  return window['go']['main']['App']['UploadFiles'](arg1);
}
